export default {
    icon: require('@/src/assets/images/icon.png'),
    petAvatar: require('@/src/assets/images/pet-avatar.png'),
    petAvatar2: require('@/src/assets/images/pet-avatar2.png'),
    userAvatar: require('@/src/assets/images/user-avatar.png'),
    adaptiveIcon: require('@/src/assets/images/adaptive-icon.png'),
    splashIcon: require('@/src/assets/images/splash-icon.png'),
    cat01: require('@/src/assets/images/pets/cats/cat01.jpg'),
    cat02: require('@/src/assets/images/pets/cats/cat02.jpeg'),
    cat03: require('@/src/assets/images/pets/cats/cat03.jpg'),
    cat04: require('@/src/assets/images/pets/cats/cat04.jpg'),
    cat05: require('@/src/assets/images/pets/cats/cat05.jpg'),
    dog01: require('@/src/assets/images/pets/dogs/dog01.png'),
    dog02: require('@/src/assets/images/pets/dogs/dog02.jpg'),
    dog03: require('@/src/assets/images/pets/dogs/dog03.jpg'),
    dog04: require('@/src/assets/images/pets/dogs/dog04.jpg'),
    dog05: require('@/src/assets/images/pets/dogs/dog05.jpg'),
    dog06: require('@/src/assets/images/pets/dogs/dog06.jpg'),
}